### PR TITLE
Apply `pyupgrade --py36-plus` to examples,svgwrite,tests

### PR DESCRIPTION
**Pull request by eumiro**
Modernize code to Python 3.6+ using `pyupgrade --py36-plus`, which changes automatically:

1. removes the encoding info from files (utf-8 is standard)
2. Python3 class syntax (default inheritance from `object` needed)
3. apply f-strings where it looks good
4. default arguments for `super()`
5. remove redundant parentheses

### CODE REVIEW

**Comment by mozman** [comment]
Does not pass tests.

**Comment by eumiro** [comment]
> Does not pass tests.

That's what really surprises me. I'd prefer to find the problem (maybe it is a bug in `pyupgrade` that can be reported?) rather than just ignore it. The tests are green on my computer.

**Comment by eumiro** [comment]
@mozman, could you just leave the PR open, please? So that I can see the CI results.

**Comment by mozman** [comment]
I don't care much about this package (I don't use it), so I don't invest any time to solve problems.

This package should stay as it is -- forever.

**Comment by eumiro** [comment]
Then please state so in the documentation.

**Pull request closed without merging**
