### PR TITLE
Allow disabling target in links

### PR DESCRIPTION
**Pull request by mitar**

### CODE REVIEW

**Comment by mozman** [comment]
Please create future pull request for the `develop` branch, added this changes manually.

**Comment by mitar** [comment]
Oh, sorry. Forgot to do that.

BTW, I think it would work just changing the target branch of this PR and then merging. You should be able to do that from your side as well. For the future.

**Comment by mozman** [comment]
Can you show me how to change the target branch at GitHub.

**Comment by mitar** [comment]
https://help.github.com/en/articles/changing-the-base-branch-of-a-pull-request

**Comment by mitar** [comment]
It is a relatively new feature.

**Pull request closed without merging**
