### PR TITLE
Some code cleanup proposal

### PR DESCRIPTION
**Pull request by Djailla**
- Unify line endings to Unix style
- Remove some old debug
- Cleanup some python2 artifacts
- Fix some syntax errors

### CODE REVIEW

**Comment by Djailla** [comment]
Hello @mozman would you like me to give a try enabling `black` or `pylama` for some automatics lint checks ?

**Comment by mozman** [comment]
I doubt I will have time or the will to check all this changes.

**Comment by Djailla** [comment]
@mozman the one in the PR ? Or the ones coming from linters ?

**Comment by mozman** [comment]
I will accept the 'Fix syntax Error' as separate PR.

I will not accept 'Fix mixed line endings'.

Other changes also as separate PR in small portions.

**Pull request closed without merging**
