### PR TITLE
extensions: add module polygons

### PR DESCRIPTION
**Pull request by ya-induhvidual**
contains functions to create regular polygons

### CODE REVIEW

**Comment by ya-induhvidual** [comment]
ok, no propb. I have now done this without a factory.
Which is actually good. I would like to add more functions to this module 
to created polygons haveing a teethed egde for finger-joints (as used in laser cutting). 
But this would be a separate pull request, if you wanted this at all.

**Comment by mozman** [comment]
This will probably annoy you, but I had another [idea](https://github.com/mozman/svgwrite/pull/47#issuecomment-488557225), but it will fit to your idea of adding more shapes.

**Comment by ya-induhvidual** [comment]
just seen it, seems reasonable :) 
 As for the transformations, I like the way openscad is doing this, so instead of having them as functions of the shapes-module, put them in a separate one and try to make them work even with basic shapes. How does that sound ? 
Anyway, I can work on this on saturday earliest.

**Comment by mozman** [comment]
An advantage of the generator approach would be, it could be used with any package which supports a kind of polygons, like my ezdxf package (closed LWPOLYLINE). Maybe your create your own generic python package for 2d shapes, a quick google search did not return a generic package, every result is linked to a graphic library.

**Comment by mozman** [comment]
I could contribute some shapes (MIT licensed) from my [ezdxf](https://github.com/mozman/ezdxf/tree/master/ezdxf/math) package:

- bezier curves
- B-splines
- euler spiral

All of them approximated by just vertices.

**Comment by ya-induhvidual** [comment]
OK, probably I misunderstood you. By generator you mean that it just returns a list of points. (tuples with two elements). That sounds fine to me.

**Comment by mozman** [comment]
A [generator](https://anandology.com/python-practice-book/iterators.html#generators) `yield` values, in this case (x, y) tuples.

**Comment by ya-induhvidual** [comment]
ok, just to confirm : to implement rotation, scale and center,  a generator-based approach would first need to get all points, calculate the centroid according to https://en.wikipedia.org/wiki/Centroid  and then rotate, scale, translate according to this (using yield). Is that what you are thinking of?

**Comment by ya-induhvidual** [comment]
Or do you expect to do the rotation and scaling etc around (0,0) ?

**Comment by mozman** [comment]
Keep it simple, just implement the basic operations:
- scaling at (0, 0)
- rotation at (0, 0)
- translation

As example, to rotate around another point (x, y), just translate(-x, -y), rotate(), translate(x, y), don't be concerned about speed, first it is Python - it is never fast and second, you can only avoid function calls (which are slow in Python) but not the operations itself, and generator calls are faster than function calls.

**Comment by mozman** [comment]
Simple implementation without tests and checks:
```
import math

def translate(vertices, dx, dy):
    for x, y in vertices:
        yield (x+dx, y+dy)

def scale(vertices, sx, sy):
    for x, y in vertices:
        yield (x*sx, y*sy)

def rotate(vertices, delta):
    for x, y in vertices:
        r = math.hypot(x, y)
        angle = math.atan2(y, x) + delta
        yield (r*math.cos(angle), r*math.sin(angle))

# Example:
v = [(1, 2), (3, 4), (5, 6)]

# rotation center
x1 = 3
y1 = 4

result = list(
    translate(
        rotate(
            translate(v, dx=-x1, dy=-y1), 
            delta=math.pi / 6
        ), 
        dx=x1, dy=y1
    )
)

```

**Comment by mozman** [comment]
Second approach would be an object oriented way with a fluent interface:
```
class Shape:
    def __init__(self, vertices):
        self.vertices = list(vertices)

    def translate(self, dx, dy):
        self.vertices = [(x + dx, y + dy) for x, y in self.vertices]
        return self

    def scale(self, sx, sy):
        self.vertices = [(x * sx, y * sy) for x, y in self.vertices]
        return self

    def rotate(self, delta):
        def _rotate(vertices):
            for x, y in vertices:
                r = math.hypot(x, y)
                angle = math.atan2(y, x) + delta
                yield (r * math.cos(angle), r * math.sin(angle))
        self.vertices = list(_rotate(self.vertices))
        return self

# rotation center
x1 = 3
y1 = 4

result = Shape([(1, 2), (3, 4), (5, 6)]).translate(-x1, -y1).rotate(math.pi/6).translate(x1, y1)

```

**Comment by ya-induhvidual** [comment]
Here is the functional generator based interface.

**Pull request merged**
